### ISSUE TITLE
XmlModel MaxLength and FixedLength types

### ISSUE THREAD

**Issue by richardv** [hamish-milne/EdmxToEfCore#1]
In the Edmx TypeBase class you have both MaxLength and FixedLength as ints.
In this extract from my edmx, MaxLength is the string "Max" from an nvarchar(max), and FixedLength is a bool.
`<Property Name="Description" Type="String" Nullable="false" MaxLength="Max" FixedLength="false" Unicode="true" />`

**Comment by hamish-milne** [comment]
Fixed with #2 . Thank you very much for the contribution!
